name: mainr

on:
  workflow_run:
    workflows: ["mainx"]
    types:
      - completed

jobs:
  retrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Log Workflow Run Conclusion
        run: |
          echo "Previous RDP workflow run concluded with: ${{ github.event.workflow_run.conclusion }}"
          echo "Triggering new RDP workflow run"

      - name: Trigger RDP Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/mainx.yml/dispatches \
            -d '{"ref":"main"}'
